#数据库连接配置
PPS :
    host : 10.40.6.150
    port : 3306
    user : java-service
    passwd : java123456
    db : pay
    charset : utf8
    
PLM :
    host : 192.168.0.202
    port : 3306
    user : plm_all
    passwd : plm_all_pw
    db : plm_new
    charset : utf8
    
PMS :
    host : 192.168.7.165
    port : 3306
    user : pms_bus_acc
    passwd : pmsERPtest
    db : pms_new
    charset : utf8
    
SPM :
    host : 192.168.0.202
    port : 3306
    user : provider_wr
    passwd : bLipJo4y
    db : provider_new
    charset : utf8
    
ISS :
    host : 192.168.0.202
    port : 3307
    user : iss_all
    passwd : ^V8E$#&2Cx
    db :
    charset : utf8
    
PDM :
    host : 192.168.0.202
    port : 3307
    user : test_user
    passwd : ronly2016@TEST
    db : pdm_1014
    charset : utf8

OBS :
    host : 10.40.6.26
    port : 3306
    user : gb_m_user
    passwd : fEtWqVMzBC
    db : obs_pay_base
    charset : utf8